### ISSUE TITLE
[BUG] Inquisitoren können keine Inventare mehr anschauen

### ISSUE THREAD

**Issue by DarkGamingShadow** [MinecraftCrowned/BugReport#1]
Wenn man als **Inquisitor** mit einem Stick auf einen Spieler rechts klickt, dann werden keine Inventare Durchsuchungsanfragen mehr versendet. Das ist bei allen Inquisitoren so und bei Wachen funktioniert es noch normal.

**Comment by oOHiyoriOo** [comment]
@SatsuyaSystems ist das vielleicht einfach ein permission issue?

**Comment by SatsuyaSystems** [comment]
Ja was war ein Permission Issue. Wir haben fürs Kampfevent das feature ausgeschaltet um Fairness zu garantieren.

Die Permissions wurden wieder richtig eingestellt und das Problem wurde somit behoben.
